apiVersion: v1
kind: Pod
metadata:
  name: hvac-log680
  namespace: exemple-log680
spec:
  containers:
    - name: hvac-controller
      image: dockervboivin/test:latest
      envFrom:
        - configMapRef:
            name: hvac-config
        - secretRef:
            name: hvac-token
      resources:
        requests:
          memory: "15Mi"
          cpu: "20m"
        limits:
          memory: "30Mi"
          cpu: "40m"
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  imagePullSecrets:
    - name: dockerhub-credentials

